## 1. OOP Fundamentals

### What is OOP?

**Procedural programming:**
- Code as a sequence os steps
- Great for data analysis

**Object-oriented programming:**
- Code as interactions of objects
- Great for building frameworks and tools
- Maintanable and more usable

**Objects as data structures:**
- Object = state + behavior
    - object -> a customer
    - state -> email = lara@company.com, phone = 398320323
    - behavior -> place order, cancel order
- state dan behavior dibundel bersamaan, biasa disebut encapsulation

---
- Class merupakan seperti blueprint dari object
- Pada python semuanya yang merupakan object, seperti number, string, dataframe, function memiliki class

- state information berisi attribute, sedangkan behavior information berisi method

**object = attributes + methods**
- attribute -> variables -> obj.my_attribute
- method -> function -> obj.my_method()

### Class anatomy: atributes and methods

In [1]:
# class <name> : starts a class definition
class Customer:

    # code inside class is indented
    # Code for class goes here
    pass # Initialize empty class

# use ClassName() to create an object of ClassName
c1 = Customer()
c2 = Customer()

In [1]:
# Add methods to a class

class Customer:

    def identify(self, name): # use self as 1st argument in method definition, harus ada
        print("I am Customer " + name)

cust = Customer()
cust.identify("Nia") #ignore self when calling method on an object

I am Customer Nia

Apa itu self?

- **class** adalah template, gimana caranya ambil data dari suatu object?
- Object dari class belum ada ketika kita hanya mendefinisikan class, tetapi kita sering butuh untuk ngambil data dari suatu object didalam class. Ini tujuan dari self, ada untuk object yang akan digunakan di dalam class.
- harus jadi argument pertama dalam method apapun

- Encapsulation: bundling data with methods that operate on data

- contoh: Customer's name harus menjadi atribute
- Attribute dibuat dengan tanda =

In [8]:
#Add an attribute to class
class Customer:
    #set the name attribute of an object to new_name
    def set_name(self, new_name):
        #Create an attribute by assigning a value
        self.name = new_name # <-- will create .name when set_name is called

    def identify(self):
        print("I am Customer " + self.name)

cust = Customer()   # <-- .name dosent exist here yet
cust.set_name("Nia Ulan Sari") # <-- .name is created and set to "Nia Ulan Sari"
cust.identify()

I am Customer Nia Ulan Sari

In [9]:
class MyCounter:

    def set_count(self, n):
        self.count = n

mc = MyCounter()
mc.set_count(5)
mc.count = mc.count + 1
print(mc.count)

6

In [37]:
class Employee:
    
    def set_name(self, new_name):
        self.name = new_name

    def set_salary(self, new_salary):
        self.salary = new_salary

    def give_raise(self, salary_raise):
        self.salary = self.salary + salary_raise

    def monthly_salary(self):
        self.mon_sal = self.salary / 12

        return self.mon_sal

emp = Employee()
emp.set_name("Korel Rossi")
emp.set_salary(50000)

mon_sal = emp.monthly_salary()
print(emp.name)
print(emp.salary)
print(mon_sal)


# emp.give_raise(1500)
# print(emp.salary)

Korel Rossi
50000
4166.666666666667

### Class anatomy: the __init__ constructor

**Methods and attributes:**
- Methods are function definitions within a class
- self as the first argument
- Define attributes by assignment
- Refer to attributes in class via self.___

**Constructor**
- Add data to object when creating it?
- Constructor __init__() method is called every time an object is created
- Init constructor juga bagus untuk set default values untuk attribute
- Define attributes in the constructor gunanya:
    - easier to know all the attributes
    - attributes are created when the object is created
    - more usable and maintainable

---------------------------------------------------------------
**BEST PRACTICE!!!**
1. Initialize attributes in __init__()

2. Naming:
    - CamelCase for classes
    - lower_snake_case for functions and attributes

3. Keep self as self
    
    contoh: 
    class MyClass:
    #This works but isnt recommended
    def my_method(kitty, attr):
        kitty.attr = attr

4. Use docstrings

    class MyClass:
    """This class does nothing"""
    pass

In [3]:
class Customer:
    def __init__(self, name):
        self.name = name # <-- Create the .name attribute and set it to name parameter
        print("The __init__ method was called")

c = Customer("Nia")
print(c.name)

The __init__ method was called
Nia

In [6]:
class Customer:
    def __init__(self, name, balance=0): # <-- set default value balance jadi 0
        self.name = name # <-- Create the .name attribute and set it to name parameter
        self.balance = balance # <-- ballance attribute added
        print("The __init__ method was called")

c = Customer("Nia")
print(c.name)
print(c.balance)

The __init__ method was called
Nia
0

In [1]:
# Add a class constructor 

class Employee:
    #Create __init__() method
    def __init__(self, name, salary=150000):
        #Create the name and salary attributes
        self.name = name
        self.salary = salary

    def give_raise(self, amount):
        self.salary += amount

    def monthly_salary(self):
        # self.mon_sal = self.salary / 12
        return self.salary / 12

emp = Employee("Nia Ulan Sari")
print(emp.name)
print(emp.salary)
print(emp.monthly_salary())

Nia Ulan Sari
150000
12500.0

In [8]:
class Employee:
  
    def __init__(self, name, salary=0):
        self.name = name
        # Modify code below to check if salary is positive
        if salary > 0:
            self.salary = salary
        else:
            self.salary = 0
            print("Invalid salary!")
      
emp = Employee("Korel Rossi", -1000)
print(emp.name)
print(emp.salary)

Invalid salary!
Korel Rossi
0

In [2]:
from datetime import datetime

class Employee:

    def __init__(self, name, salary=0):
        self.name = name
        if salary > 0:
            self.salary = salary
        else:
            self.salary = 0
            print("Invalid salary!")


        self.hire_date = datetime.today()

emp = Employee("Nia Ulan Sari", -1000)
print(emp.name)
print(emp.salary)
print(emp.hire_date)

Invalid salary!
Nia Ulan Sari
0
2021-11-03 15:53:08.976605

In [17]:
# Write a class from scratch
import math

class Point:

    def __init__(self, x=0.0, y=0.0):
        self.x = x
        self.y = y

    def distance_to_origin(self):
        return math.sqrt((self.x ** 2) + (self.y ** 2))

    def reflect(self, axis):
        if axis == "x":
            self.y = -self.y
        elif axis == "y":
            self.x = -self.x
        else:
            print("Error")

pt = Point(x=3.0)
pt.reflect("y")
print((pt.x, pt.y))
pt.y = 4.0
print(pt.distance_to_origin())

(-3.0, 0.0)
5.0

## 2. Inheritance and Polymorphism

### Instance and class data

**Core principles of OOP:**
1. Inheritance:
    - Extending functionality of existing code 
2. Polymorphism
    - Creating a unified interface
3. Encapsulation 
    - Bundling odf data and methods

**CLASS-LEVEL DATA:**
- Data shared among all instances of a class
- Define class attributes in the body of class

**Why use class attributes?**
- Global constants related to the class
- minimal/maximal values for attributes
- commonly used values and consants, e.g. pi for a Circle class

**Class methods:**
- Methods are already "shared": same code for every instance
- Class methods cant use instance-level data

**Kenapa class methods dibutuhkan?:**
- The main use case is alternative constructor
- Sebuah class cuma bisa punya 1 init method, tapi mungkin terdapat bbrp cara untuk inisialisasi object
- Use class methods to create objects

In [3]:
#Instance-level data

class Employee:
    def __init__(self, name, salary): #name, salary = instance attributes
        self.name = name 
        self.salary = salary

emp1 = Employee("Nia", 230232)
emp2 = Employee("Engkau", 322)

In [ ]:
#Class-level data

class MyClass:
    #Define a class attribute
    CLASS_ATTR_NAME = attr_value # Merupakan global variable

In [19]:
# Class-level data

class Employee:
    #Define a class attribute
    MIN_SALARY = 30000 #<-- no self, is shared among all instances

    def __init__(self, name, salary):

        self.name = name 
        #Use class name to access class attribute (ClassName.ATTR_NAME)
        if salary >= Employee.MIN_SALARY:
            self.salary = salary
        else:
            self.salary = Employee.MIN_SALARY

emp1 = Employee("TBD", 40000)
print(emp1.MIN_SALARY)

emp2 = Employee("TBD", 60000)
print(emp2.MIN_SALARY)

30000
30000

In [ ]:
# Class methods

class MyClass:

    @classmethod #<---use decorator to declare a class method
    def my_awesome_method(cls, args): #<--- cls argument refers t class
        # Do stuff here
        # Cant use any instance attributes

#Call class method
MyClass.my_awesome_method(args)

In [22]:
class Employee:
    MIN_SALARY = 30000

    def __init__(self, name, salary=30000):
        self.name = name 
        if salary >= Employee.MIN_SALARY:
            self.salary = salary 
        else:
            self.salary = Employee.MIN_SALARY

    @classmethod
    def from_file(cls, filename):
        with open(filename, "r") as f:
            name = f.readline()
        return cls(name)

emp = Employee.from_file("employee_data.txt")
type(emp)

__main__.Employee

In [24]:
# Class-level attributes

#Create a Player class
class Player:

    MAX_POSITION = 10

    def __init__(self, positions=0):
        self.position = position

print(Player.MAX_POSITION)

p = Player()
print(p.MAX_POSITION)

10
10

In [26]:
# Class-level attributes

#Create a Player class
class Player:

    MAX_POSITION = 10

    def __init__(self):
        self.position = 0

    def move(self, steps):
        self.steps = steps
        if self.position + steps < Player.MAX_POSITION:
            self.position = steps + self.position
        else:
            self.position = Player.MAX_POSITION

    def draw(self):
        drawing = "-" * self.position + "|" + "-"* (Player.MAX_POSITION - self.position)
        print(drawing)
    

p = Player(); p.draw()
p.move(4); p.draw()
p.move(4); p.draw()
p.move(3); p.draw()

|----------
----|------
--------|--
----------|

In [27]:
# Changing class attributes

#Create a Player class
class Player:

    MAX_POSITION = 10
    MAX_SPEED = 3

    def __init__(self):
        self.position = 0

    def move(self, steps):
        self.steps = steps
        if self.position + steps < Player.MAX_POSITION:
            self.position = steps + self.position
        else:
            self.position = Player.MAX_POSITION

    def draw(self):
        drawing = "-" * self.position + "|" + "-"* (Player.MAX_POSITION - self.position)
        print(drawing)
    
p1 = Player(); p2 = Player()
print(p1.MAX_SPEED); print(p2.MAX_SPEED)
p1.MAX_SPEED = 7
print(p1.MAX_SPEED); print(p2.MAX_SPEED)
print(Player.MAX_SPEED)

3
3
7
3
3

In [30]:
p1 = Player(); p2 = Player()
print(p1.MAX_SPEED); print(p2.MAX_SPEED)
Player.MAX_SPEED = 7
print(p1.MAX_SPEED); print(p2.MAX_SPEED)
print(Player.MAX_SPEED)

3
3
7
7
7

In [36]:
#Alternative constructor

class BetterDate:
    #Constructor
    def __init__(self, year, month, day):
        self.year, self.month, self.day = year, month, day

    #Define class method from_str
    @classmethod
    def from_str(cls, datestr):
        #Split the string at "-" and convert each part to integer
        parts = datestr.split("-")
        year, month, day = int(parts[0]), int(parts[1]), int(parts[2])

        # Return class instance
        return cls(year, month, day)

bd = BetterDate.from_str('2000-02-24')
print(bd.year)
print(bd.month)
print(bd.day)

2000
2
24

In [42]:
from datetime import datetime

class BetterDate:
    def __init__(self, year, month, day):
        self.year, self.month, self.day = year, month, day

    @classmethod
    def from_str(cls, datestr):
        year, month, day = map(int, datestr.split("-"))
        return cls(year, month, day)

    @classmethod
    def from_datetime(cls, datetime):
        year, month, day = datetime.year, datetime.month, datetime.day
        return cls(year, month, day)
    
today = datetime.today()
bd = BetterDate.from_datetime(today)
print(bd.year)
print(bd.month)
print(bd.day)

2021
9
3

### Class Inheritance

>OOP = Code reuse

1. Someone has already done it 
    - Modules are great for fixed functionality
    - OOP is great for customizing functionality
2. DRY: Dont Repeat Yourself 

**Inheritance:** 
- New class functionality = Old class functionality + extra

**Implementing class inheritance:**

```python
Class MyChild(MyParent):
    #Do stuff here
```

- MyParent: class whose functionality is being extended/inherited
- MyChild: class thet will inherit the functionality and add more
- Child class has all of the parent data

In [58]:
class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def withdraw(self, amount):
        self.balance -= amount

#Empty class inherited from BankAccount
class SavingsAccount(BankAccount):
    pass

savings_acct = SavingsAccount(1000)
type(savings_acct)

#Attribute inherited from BankAccount
savings_acct.balance
#Method inherited from BankAccount
savings_acct.withdraw(300)
print(isinstance(savings_acct, SavingsAccount))
print(isinstance(savings_acct, BankAccount))

acct = BankAccount(500)
print(isinstance(acct, SavingsAccount))

print(isinstance(acct, BankAccount))

True
True
False
True

In [63]:
# Create a subclass

class Employee:
  MIN_SALARY = 30000    

  def __init__(self, name, salary=MIN_SALARY):
      self.name = name
      if salary >= Employee.MIN_SALARY:
        self.salary = salary
      else:
        self.salary = Employee.MIN_SALARY
        
  def give_raise(self, amount):
      self.salary += amount      
        
# Define a new class Manager inheriting from Employee
class Manager(Employee):
    def display(self):
        print("Manager " + self.name)

# Define a Manager object
mng = Manager("Nia Ulan Sari", 10000)

# Print mng's name
print(mng.name)
mng.display()

Nia Ulan Sari
Manager Nia Ulan Sari

### Customizing functionality via inheritance

Adding functionality:
    - Add methods as usual
    - Can use the data from both parent and child class

In [76]:
class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def withdraw(self, amount):
        self.balance -= amount

#Empty class inherited from BankAccount
class SavingsAccount(BankAccount):
    #Constructor speficially for SavingsAccount with an additional parameter
    def __init__(self, balance, interest_rate):
        #Call the parent constructor using ClassName.__init__()
        BankAccount.__init__(self, balance) #<--self is a savingsAccount but also a BankAccount
        
        #Add more functionality
        self.interest_rate = interest_rate

        #New functionality
    def compute_interest(self, n_periods = 1):
            return self.balance * ((1 + self.interest_rate) ** n_periods - 1)

acct = SavingsAccount(1000, 0.03)
acct.interest_rate
acct.compute_interest(2)

60.899999999999956

In [14]:
# Customizing functionality
# Polymorphism = meletakkan method di child class yang mana namanya sama dengan method di parent class

class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def withdraw(self, amount):
        self.balance -= amount

#Empty class inherited from BankAccount
class SavingsAccount(BankAccount):
    #Constructor speficially for SavingsAccount with an additional parameter
    def __init__(self, balance, interest_rate):
        #Call the parent constructor using ClassName.__init__()
        BankAccount.__init__(self, balance) #<--self is a savingsAccount but also a BankAccount
        #Add more functionality
        self.interest_rate = interest_rate

    #New functionality
    def compute_interest(self, n_periods = 1):
            return self.balance * ((1 + self.interest_rate) ** n_periods - 1)

class CheckingAccount(BankAccount):
    def __init__(self, balance, limit):
        BankAccount.__init__(self, balance)
        self.limit = limit

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount, fee=0):
        if fee <= self.limit:
            BankAccount.withdraw(self, amount - fee)
        else:
            BankAccount.withdraw(self, amount - self.limit)


# acct = SavingsAccount(1000, 0.03)
# acct.interest_rate
# acct.compute_interest(2)

check_acct = CheckingAccount(1000, 25)
#Call withdraw from CheckingAccount
print(check_acct.withdraw(200, fee=15))

bank_acct = BankAccount(1000)

#Call withdrar from BankAccount
print(bank_acct.withdraw(200))

None
None

In [15]:
# Contoh Polymorphism

class Employee:
    def __init__(self, name, salary=30000):
        self.name = name
        self.salary = salary

    def give_raise(self, amount):
        self.salary += amount

        
class Manager(Employee):
    def display(self):
        print("Manager ", self.name)

    def __init__(self, name, salary=50000, project=None):
        Employee.__init__(self, name, salary)
        self.project = project

    # Add a give_raise method
    def give_raise(self, amount, bonus= 1.05):
        Employee.give_raise(self, amount * bonus)
    
    
mngr = Manager("Ashta Dunbar", 78500)
mngr.give_raise(1000)
print(mngr.salary)
mngr.give_raise(2000, bonus=1.03)
print(mngr.salary)

79550.0
81610.0

In [104]:
# Inheritance of class attributes

class Player:

    MAX_POSITION = 10
    MAX_SPEED = 3

    def __init__(self):
        self.position = 0

    def move(self, steps):
        self.steps = steps
        if self.position + steps < Player.MAX_POSITION:
            self.position = steps + self.position
        else:
            self.position = Player.MAX_POSITION

    def draw(self):
        drawing = "-" * self.position + "|" + "-"* (Player.MAX_POSITION - self.position)
        print(drawing)
    
class Racer(Player):
    MAX_SPEED = 5

p = Player()
r = Racer()

print("p.MAX_SPEED: ", p.MAX_SPEED)
print("r.MAX_SPEED: ", r.MAX_SPEED)

print("p.MAX_POSITION = ", p.MAX_POSITION)
print("r.MAX_POSITION = ", r.MAX_POSITION)

p.MAX_SPEED:  3
r.MAX_SPEED:  5
p.MAX_POSITION =  10
r.MAX_POSITION =  10

In [107]:
# Customizing a DataFrame

import pandas as pd

class LoggedDF(pd.DataFrame):
    
    def __init__(self, *args, **kwargs):
        pd.DataFrame.__init__(self, *args, **kwargs)
        self.created_at = datetime.today 

ldf = LoggedDF({"col1": [1,2], "col2": [3,4]})
print(ldf.values)
print(ldf.created_at)

[[1 3]
 [2 4]]
<built-in method today of type object at 0x00007FF985375650>

In [109]:
# Import pandas as pd
import pandas as pd

# Define LoggedDF inherited from pd.DataFrame and add the constructor
class LoggedDF(pd.DataFrame):
  
  def __init__(self, *args, **kwargs):
    pd.DataFrame.__init__(self, *args, **kwargs)
    self.created_at = datetime.today()
    
  def to_csv(self, *args, **kwargs):
    # Copy self to a temporary DataFrame
    temp = self.copy()
    
    # Create a new column filled with self.created_at
    temp["created_at"] = self.created_at
    
    # Call pd.DataFrame.to_csv on temp, passing in *args and **kwargs
    pd.DataFrame.to_csv(temp, *args, **kwargs)

## 3. Integrating with Standard Python

### Operator overloading: comparison

#### Object equality

When comparing two objects of a custom class using ==, Python by default compares just the object references, not the data contained in the objects.

In [2]:
class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance

cust1 = Customer("Nia Ulan Sari", 3000)
cust2 = Customer("Nia Ulan Sari", 3000)
cust1 == cust2

#Bisa membuat dua cust dengan nama dan balance yang sama

False

In [4]:
class Customer:
    def __init__(self, name, balance, id):
        self.name, self.balance, self.id = name, balance, id

cust1 = Customer("Nia Ulan Sari", 3000, 123)
cust2 = Customer("Nia Ulan Sari", 3000, 123)
cust1 == cust2

# cust1 dan cust2 tidak sama karena python membandingkan references memory bukan datanya

False

In [5]:
print(cust1)

<__main__.Customer object at 0x000001A1A2620250>

In [6]:
print(cust2)

<__main__.Customer object at 0x000001A1A2614FA0>

#### Overloading __eq__()

In [7]:
class Customer:
    def __init__(self, id, name):
        self.id, self.name = id, name

    #Will be called when == is used
    def __eq__(self, other):
        # Diagnostics printout
        print("__eq__() is called")

    # Returns True if all attributes match
        return (self.id == other.id) and (self.name == other.name)

cust1 = Customer("Nia Ulan Sari", 3000)
cust2 = Customer("Nia Ulan Sari", 3000)
cust1 == cust2

__eq__() is called

True

Other comparison operators:

- ==  -> __eq__()
- !=  -> __ne__()
- >=  -> __ge__()
- <=  -> __le__()
- >   -> __gt__()
- <   -> __lt__()

In [8]:
class BankAccount:
    # Modify to analize a number attribute
    def __init__(self, number, balance=0):
        self.balance = balance
        self.number = number

    def withdraw(self, amount):
        self.balance -= amount

    def __eq__(self, other):
        return self.number == other.number

acct1 = BankAccount(123, 1000)
acct2 = BankAccount(123, 1000)
acct3 = BankAccount(456, 1000)
print(acct1 == acct2)
print(acct1 == acct3)

True
False

In [12]:
class BankAccount:
    def __init__(self, number, balance=0):
        self.number = number
        self.balance = balance

    def withdraw(self, amount):
        self.balance -= amount

    def __eq__(self, other):
        return (self.number == other.number) and type(self) == type(other)

class Phone:
    def __init__(self, number, balance=0):
        self.number = number
        self.balance = balance

    def withdraw(self, amount):
        self.balance -= amount

    def __eq__(self, other):
        return (self.number == other.number)

acct = BankAccount(873555333)
pn = Phone(873555333)
print(acct == pn)

False

In [13]:
class Parent:
    def __eq__(self, other):
        print("Parent's __eq__() called")
        return True

class Child(Parent):
    def __eq__(self, other):
        print("Child's __eq__() called")
        return True

p = Parent()
c = Child()

p == c

Child's __eq__() called

True

### Operator overloading: string representation

In [2]:
import numpy as np

print(np.array([1, 2, 3]))

[1 2 3]

In [3]:
# __str__() 
# - informal, for end user
# - string representation

str(np.array([1, 2, 3]))

'[1 2 3]'

In [4]:
# __repr__()
# - formal, for developer
# reproducible representation
# fallback for prin()

repr(np.array([1, 2, 3]))

'array([1, 2, 3])'

In [19]:
np.array([1, 2, 3])

array([1, 2, 3])

In [24]:
#Implementation: __str__()

class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance

    def __str__(self):
        cust_str = """
        Customer:
            name: {name}
            balance: {balance}
        """.format(name = self.name, balance = self.balance)
        return cust_str


cust = Customer("Nia Ulan Sari", 3000)
print(cust)

        Customer:
            name: Nia Ulan Sari
            balance: 3000

In [7]:
# Implementation: __repr__()

class Customer:
    def __init__(self, name, balance):
        self.name, self.balance = name, balance

    def __repr__(self):
        # Notice the '..' around name
        return "Customer('{name}', {balance})".format(name = self.name, balance = self.balance)


cust = Customer("Nia Ulan Sari", 3000)
cust # <-- # Will implicitly call __repr__()

Customer('Nia Ulan Sari', 3000)

In [9]:
my_num = 5
my_str = "Hello"

f = "my_num is {}, and my_str is \"{}\".".format(my_num, my_str)
print(f)

my_num is 5, and my_str is "Hello".

In [11]:
class Employee:
    def __init__(self, name, salary=30000):
        self.name, self.salary = name, salary

    def __str__(self):
        cust = """
        Employee name: {name}
        Employee salary: {salary}""".format(name = self.name, salary = self.salary)
        return cust

emp1 = Employee("Amar Howard", 30000)
print(emp1)
emp2 = Employee("Carolyn Ramirez", 35000)
print(emp2)

        Employee name: Amar Howard
        Employee salary: 30000

        Employee name: Carolyn Ramirez
        Employee salary: 35000

In [13]:
class Employee:
    def __init__(self, name, salary=30000):
        self.name, self.salary = name, salary
      

    def __str__(self):
        s = "Employee name: {name}\nEmployee salary: {salary}".format(name=self.name, salary=self.salary)      
        return s
      
    # Add the __repr__method  
    def __repr__(self):
        return "Employee('{name}', {salary})".format(name = self.name, salary = self.salary)

emp1 = Employee("Amar Howard", 30000)
print(repr(emp1))
emp2 = Employee("Carolyn Ramirez", 35000)
print(repr(emp2))

Employee('Amar Howard', 30000)
Employee('Carolyn Ramirez', 35000)

### Exceptions handling

In [14]:
# ZeroDivisionError = error yang muncul saat ada pembagian terhadap 0
a = 1
a / 0

ZeroDivisionError: division by zero

In [15]:
#TypeError = error yang muncul saat ada operasi dengan data type berbeda
a = 1
a + "Hello"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [16]:
a = [1, 2, 3]
a[5]

IndexError: list index out of range

In [17]:
# NameError = error yang muncul saat variabel tidak didefinisikan
a = 1
a + b

NameError: name 'b' is not defined

Exception handling:

- Prevent the program from terminating when an exception is raised
- try - except - finally

In [ ]:
try:
    # Try running some code
except ExceptionNameHere:
    # Run this code if ExceptionNameHere happens
except AnotherExceptionHere:
    # Run this code if AnotherExceptionHere happens
finally:
    # Run this code no matter what

In [21]:
# Raising exceptions 
# raise ExceptionNameHere('Error mesaage here')

def make_list_of_ones(length):
    if length <= 0:
        raise ValueError("Invalid length!")
    return [1] * length

make_list_of_ones(-1)

ValueError: Invalid length!

Custom exceptions:

- Inherit from Exception or oene of its subclasses
- Usually an empty class

In [23]:
class BalanceError(Exception): 
    pass

class Customer:
    def __init__(self, name, balance):
        if balance < 0:
            raise BalanceError("Balance has to be non-negative!")
        else:
            self.name, self.balance = name, balance

cust = Customer("Nia Ulan Sari", -20000)

BalanceError: Balance has to be non-negative!

In [27]:
try:
    cust = Customer("Larry Torres", -100)
except:
    cust = Customer("Larry Torres", 0)

print(cust.name)

Larry Torres

In [1]:
# MODIFY the function to catch exceptions
def invert_at_index(x, ind):
    try:
        return 1/x[ind]
    except ZeroDivisionError:
        print("Cannot divide by zero!")
    except IndexError:
        print("Index out of range!")
 
a = [5,6,0,7]

# Works okay
print(invert_at_index(a, 1))

# Potential ZeroDivisionError
print(invert_at_index(a, 2))

# Potential IndexError
print(invert_at_index(a, 5))

0.16666666666666666
Cannot divide by zero!
None
Index out of range!
None

In [29]:
class SalaryError(ValueError):
    pass

class BonusError(SalaryError):
    pass

class Employee:
    MIN_SALARY = 30000
    MAX_BONUS = 5000

    def __init__(self, name, salary = 30000):
        self.name = name

        if salary < Employee.MIN_SALARY:
            raise SalaryError("Salary is too low!")
        self.salary = salary

    def give_bonus(self, amount):
        if amount > Employee.MAX_BONUS:
            raise BonusError("The bonus amount is to high")
        elif self.salary + amount < Employee.MIN_SALARY:
            raise SalaryError("The salary after bonus is too low!")
        else:
            self.salary += amount

- It's better to include an except block for a child exception before the block for a parent exception, otherwise the child exceptions will be always be caught in the parent block, and the except block for the child will never be executed.

- except block for a parent exception will catch child exceptions

## Designing for inheritance and polymorphism

- Polymorphism: menggunakan interface gabungan untuk mengoperasikan object dari class berbeda

Liskov substituution principle:

- Base class should be interchangeable with any of its subclasses without altering any properties of the program.

In [3]:
class Rectangle():
    def __init__(self, h, w):
        self.h = h
        self.w = w

class Square(Rectangle):
    def __init__(self, w):
        self.h = w
        self.w = w

tes = Square(4)

In [ ]:
class Rectangle():
    def __init__(self, h, w):
        self.h = h
        self.w = w

    def set_h(self, h):
        self.h = h
    
    def set_w(self, w):
        self.w = w

class Square(Rectangle):
    def __init__(self, w):
        self.h = w
        self.w = w

    def set_h(self, h):
        self.h = h
        self.w = h
    
    def set_w(self, w):
        self.w = w
        self.h = w

tes = Square(4)

### Managing data access: private attributes

- All classdata in python is technically public

#### Restricting access

- Naming conventions
- Use @property to customize access
- Overriding __getattr__() and __setattr__()

#### Naming convention: internal attributes

- obj._att_name
- obj._method_name()
- starts with single _ -> "internal"
- not a part of a public API
- as a class user: "dont touch this"
- as a class developer: use for implementation details, heler functions

#### Naming convention: pseudoprivate attributes

- obj.__attr_name
- obj.__method_name()
- Starts but doesnt end with __ -> "private"
- not inherited
- name mangling: obj.__attr_name is interpreted as obj._MyClass__attr_name
- used to prevent name clashes in inherited classes

#### Leading and trailing __ are only used or built-in python methods (__init__(), __repr__())

In [2]:
class BetterDate:

    _MAX_DAYS = 30 # internal class attribute
    _MAX_MONTHS = 12 # internal class attribute

    def __init__(self, year, month, day):
        self.year, self.month, self.day = year, month, day

    @classmethod
    def from_str(cls, datestr):
        year, month, day = map(int, datestr.split("-"))
        return (cls, year, month, day)

    def _is_valid(self): # internal class method
        if self.day <= BetterDate._MAX_DAYS and self.month <= BetterDate._MAX_MONTHS:
            return True
        else:
            return False

bd1 = BetterDate(2020, 4, 30)
print(bd1._is_valid())

bd2 = BetterDate(2020, 6, 45)
print(bd2._is_valid())

True
False

### Properties

### Changing attribute values

In [3]:
class Employee:
    def set_name(self, name):
        self.name = name
    def set_salary(self, salary):
        self.salary = salary
    def give_raise(self, amount):
        self.salary += amount

    def __init__(self, name, salary):
        self.name, self.salary = name, salary

emp = Employee("Nia Ulan Sari", 35000)
emp.salary = emp.salary + 5000

#### Control attribute access

- check the value for validity
- or make attributes read-only

In [4]:
import pandas as pd

df = pd.DataFrame({"colA": [1, 2], "colB": [3, 4]})
df

   colA  colB
0     1     3
1     2     4

In [5]:
df.columns = ["new_colA", "new_colB"]
df

   new_colA  new_colB
0         1         3
1         2         4

In [6]:
df.columns = ["new_colA", "new_colB", "extra"]
df

ValueError: Length mismatch: Expected axis has 2 elements, new values have 3 elements

In [7]:
df.shape = (43, 27)
df

<ipython-input-7-97b53e7666aa>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.shape = (43, 27)

AttributeError: can't set attribute

#### @property decorator

In [13]:
class Employer:
    def __init__(self, name, new_salary):
        self._salary = new_salary # Use "protected" attribute with leading _ to store data

    # Use @property on a method whose name is exactly of the restricted attributes 
    # return the internal attribute
    @property
    def salary(self):
        return self._salary

    # Use @attr.setter on a method attr() that will be called on obj.attr = value 
    @salary.setter 
    def salary(self, new_salary): #Untuk validasi
        if new_salary < 0:
            raise ValueError("Invalid salary")
        self._salary = new_salary

emp = Employer("Nia Ulan Sari", 35000)
#Accessing the "properti"
print(emp.salary)
emp.salary = 60000 # <--@ salary.setter
print(emp.salary)

35000
60000

#### Other possibilities

- Do not add @attr.setter -> create a read-only property
- Add @attr.getter -> use for the method that is called when the property's value is retrieved
- Add @attr.deleter -> use for the method that is called when the property is deleted using del

In [22]:
class Customer:
    
    def __init__(self, name, new_bal):
        self.name = name

        # if new_bal < 0:
        #     raise ValueError("Invalid balance!")
        # self._balance = new_bal

    @property
    def balance(self):
        return self._balance

    @balance.setter
    def balance(self, new_bal):
        if new_bal < 0:
            raise ValueError("Invalid balance")
        self._balance = new_bal
        print("Setter method is called")

cust = Customer("Belinda Lutz", 2000)
cust.balance = 3000
print(cust.balance)

Setter method is called
3000

In [26]:
import pandas as pd
from datetime import datetime

class LoggedDF(pd.DataFrame):
    def __init__(self, *args, **kwargs):
        pd.DataFrame.__init__(self, *args, **kwargs)
        self._created_at = datetime.today()

    def to_csv(self, *args, **kwargs):
        temp = self.copy()
        temp["created_at"] = self._created_at
        pd.DataFrame.to_csv(temp, *args, **kwargs)

    @property
    def created_at(self):
        return self._created_at 


ldf = LoggedDF({"col1": [1, 2], "col2":[3, 4]})

ldf.created_at = '2035-07-13'
print(ldf.created_at)

AttributeError: can't set attribute

Yang bisa dipelajari selanjutnya: 
- Multiple inheritance and mis-in classes 
- Overriding built-in operators like +
- __getatts__() dan __setattr__()
- custom iterators
- Abstract base classes
- Dataclasses

Design: 
- SOLID principles: 

    - Single-responsibility principle
    - Open-closed principle
    - Liskov substitution principle
    - Interface segregation principle 
    - Dependency inversion principle

In [29]:
import numpy as np

class Operations:
  def __init__(self, array_1):
    self.A = array_1 
  def Maximum(self):
    """Returns maximum
       value of an array"""
    return np.amax(self.A)
op_obj = Operations(np.array([7, 2, 2]))
print(op_obj.Maximum())

7

In [22]:
import math 

class Rectangle:
    def __init__(self, height, weight):
        self.height = height
        self.weight = weight
        
    def area(self):
        return self.height * self.weight
        

class Circle:
    def __init__(self, r):
        self.r = r
        
    def area(self):
        return math.pi * (self.r * self.r)

In [23]:
r = Rectangle(2, 3)
print(r.area())

6

In [24]:
c = Circle(1)
print(c.area())

3.141592653589793

In [35]:
class Car:
    def __init__(self, max_speed, s):
        self.max_speed, self.s = max_speed, s
        
    def __repr__(self):
        return "Car with the maximum speed of {max} {s}".format(max = self.max_speed, s = self.s) 
    

class Boat:
    def __init__(self, max_speed):
        self.max_speed = max_speed
        
    def __repr__(self):
        return "Boat with the maximum speed of {max} knots".format(max = self.max_speed)

In [39]:
c = Car(10, 'mph')
print(c)
b = Boat(5)
print(b)

Car with the maximum speed of 10 mph
Boat with the maximum speed of 5 knots